management_sistem/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('usuarios/', include("user.urls")),
    path('ordens/', include("order.urls")),
    path('produtos/', include("product.urls")),
    path('', include("dashboard.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Sistema de Gestão'
admin.site.index_title= 'Administração'
admin.site.site_title = 'Seja bem vindo a gestão de produtos e serviços'

product/urls.py
from django.urls import path
from . import views
from .views import ProductDetailView, ProductUpdateView, ProductCreateView

app_name = "product"

urlpatterns = [
    path('', views.products, name='home'),
    path('delete/<int:pk>/', views.product_delete,name='delete'),
    path('detalhe/<slug:slug>/', ProductDetailView.as_view(),name='detail'),
    path('update/<slug:slug>/', ProductUpdateView.as_view(),name='update'),
    path('criar/', ProductCreateView.as_view(),name='create'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user import views as user_views

app_name = 'user'

urlpatterns = [
    # Login
    path('login', auth_views.LoginView.as_view(
        template_name='user/login.html'), name='login'),
    # Logout
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'),
         name='logout'),
    # Cadastro
    path('registro/', user_views.register, name='register'),
    # Perfil
    path('perfil/', user_views.profile, name='profile'),
    
    path('perfil/update/', user_views.profile_update,
         name='update'),    
    ]

product/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from model_utils.models import TimeStampedModel
from autoslug import AutoSlugField



class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_available=True)


class Category(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:list_by_category", kwargs={"slug": self.slug})

    class Meta :
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

class Product(models.Model): 
    category = models.ManyToManyField(Category, related_name="products", blank=True)   
    name = models.CharField('Nome',max_length=100)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    description = models.TextField('Descrição',max_length=500, blank=True)
    reference_code = models.IntegerField('Código de Referência')
    internal_code=models.IntegerField('Código Interno', null=True)
    price = models.DecimalField('Preço',max_digits=10, decimal_places=2)
    image = models.ImageField('Imagem', upload_to="products/%Y/%m/%d", blank=True)
    # TODO weight = models.DecimalField('Peso', default=0, blank=True, max_digits=10, decimal_places=3)
    is_available = models.BooleanField('Disponivel', default=True)

    # available = AvailableManager()
    
    def __str__(self):
        return f'{self.name}-{self.pk}'
    
    def get_absolute_url(self):
        return reverse("product:detail", kwargs={"slug": self.slug})
            
    class Meta :
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"

product/forms.py
from django import forms
from .models import Product
from order.models import Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'description', 'reference_code', 'price',  'image', 'is_available']


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['sale', 'reference_code', 'price', 'customer', 'description', 'description_2']

product/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from order.models import Order
from .models import Product
from .forms import ProductForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic import DetailView
from django.contrib import messages

# Create your views here.

# @login_required(login_url='user-login')
def products(request):
    product = Product.objects.all()
    product_count = product.count()
    customer = User.objects.filter(groups=2)
    customer_count = customer.count()
    order = Order.objects.all()
    order_count = order.count()
    # Pesquisa por nome '''Não funciona caso não haja busca'''
    search = request.GET.get('search', None)
    if search :
        product = product.filter(name__icontains=search)|product.filter(id=search)
        
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            product_name = form.cleaned_data.get('name')
            messages.success(request, f'{product.name} Foi adicionado')
            return redirect('product:home')
    else:
        form = ProductForm()
    context = {
        'product': product,
        'form': form,
        'customer_count': customer_count,
        'product_count': product_count,
        'order_count': order_count,
    }
    
    
    return render(request, 'product/products.html', context)


# @login_required(login_url='user-login')
class ProductDetailView(DetailView):
    
    model = Product
    template_name= 'product/product_detail.html'
    
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        return context

class ProductUpdateView(UpdateView):    
    model = Product
    fields = ['name', 'category','description', 'reference_code', 'price', 'image',]
    template_name_suffix = '_edit'
    
    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            messages.success(request, 'Produto atualizado com sucesso.') 
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    # def get_object(self):
    #     return Product.objects.get(pk=self.request.GET.get('pk')) 

class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'category', 'description', 'reference_code', 'price', 'image']
    
    
# TODO : @login_required(login_url='user-login')
# @allowed_users(allowed_roles=['Admin'])
def product_delete(request, pk):
    item = Product.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('product:home')
    context = {
        'item': item
    }
    return render(request, 'product/products_delete.html', context)

def product_edit(request, pk):
    item = Product.objects.get(id=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('product:home')
    else:
        form = ProductForm(instance=item)
        product = Product.objects.get(id=pk)
        context = {
            'product': product,
            'form': form,
        }
    return render(request, 'product/products_edit.html', context)

templates/product/product_detail.html
{% extends 'base.html' %}
{% block title %}Detalhes dos Produtos{% endblock %}
{% block content %}

<div class="app-wrapper">	    
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
            <div class="row my-4">
                <div class="col-md-6 offset-md-3 p-3 bg-white">
                    <h3>{{ product.name }}</h3><hr>
                    <h4>Categoria(s) : {% for cat in product.category.all %}{{cat.name}}{%endfor%} </h4>
                    <hr>
                    <h4>Descrição : {{product.description}}</h4>
                    <h4>Código de referência : {{product.reference_code}}</h4>
                    <h4>Preço : R$ {{product.price}}</h4>
                </div>
            </div>
        </div><!--//container-fluid-->
    </div><!--//app-content-->	    
</div><!--//app-wrapper-->  
{% endblock %}

templates/product/product_edit.html
{% extends 'base.html' %}
{% block title %}Edição do produto{% endblock %}
{% load crispy_forms_tags %}

{% block content %}

<div class="app-wrapper">	    
	    <div class="app-content pt-3 p-md-3 p-lg-4">
		    <div class="container-xl">			    
			    <h1 class="app-page-title">Produto : {{product.name}} </h1> 
                <div class="row col-10">
                    <div class="row my-4">
                        <div class="col-md-6 offset-md-3 p-3 bg-white">
                            <h3>Formulário do Produto</h3>
                            <hr>
                            <form method="post">{% csrf_token %}
                                {{ form|crispy }}
                                <input type="submit" value="Atualizar">
                            </form>
                        </div>
                    </div>
                </div>
        </div><!--//container-fluid-->
    </div><!--//app-content-->	    
</div><!--//app-wrapper-->  
{% endblock %}

templates/product/product_form.html
{% extends "base.html"%}
{% block title %}Criação {% endblock title%}
{% block content %}

{% load crispy_forms_tags %}

<div class="app-wrapper">	    
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
            <h1 class="app-page-title">Criar novo Produto </h1>
            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Salvar">
            </form>
        </div><!--//container-fluid-->
    </div><!--//app-content-->	    
</div><!--//app-wrapper-->  

{% endblock content%}

templates/product/products.html
{% extends 'base.html' %}
{% block title %}Página de Produtos{% endblock %}
{% load crispy_forms_tags %}

{% block content %}

<div class="app-wrapper">	    
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">			    
            <div class="col-auto mt-5">
                <form class="docs-search-form row gx-1 align-items-center">
                    <div class="col-auto">
                        <input type="text"  name="search" class="form-control" placeholder="Busque produtos aqui">
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn app-btn-secondary">Buscar</button>
                    </div>
                </form>							
            </div><!--//col-->
            <h1 class="app-page-title">Lista de Produtos </h1>
                <div class="row my-4">

                    <div class="col-md-2">
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="col-md-10">
                        <table class="table bg-white">
                            <thead class="bg-info text-white">
                                <tr>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Descrição</th>
                                    <th scope="col">Preço ($)</th>
                                    <th scope="col">Atividades</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product in product %}
                                <tr>
                                    <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                                    <td>{{ product.description|truncatewords:2 }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>
                                        <a class="btn btn-info btn-sm mr-2"
                                            href="{% url 'product:update' product.slug %}"><i class="fas fa-edit"></i></a>
                                        <a class="btn btn-danger btn-sm ml-2"
                                            href="{% url 'product:delete' product.id %}"><i class="fas fa-times"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div><!--//container-fluid-->
	    </div><!--//app-content-->	    
    </div><!--//app-wrapper-->  

{% endblock %}

templates/product/products_delete.html
{% extends 'base.html' %}
{% block title %}Deletar Produto{% endblock %}

{% load crispy_forms_tags %}
{% block content %}


<div class="app-wrapper">	    
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
            <div class="row col-10">
                <div class="row my-4">
                    <div class="col-md-6 offset-md-3">
                        <div class="border p-3 bg-white">
                            <h3>Excluir Produto</h3>
                            <hr>
                            <form method="POST">
                                <div class="alert alert-danger">
                                    <h4>Tem certeza que deseja excluir o produto "{{ item.name }}" ? <br>Lembre-se que essa ação é irreversível</h4>
                                </div>
                                {% csrf_token %}
                                {{ form|crispy }}
                                <a class="btn btn-secondary btn-sm" href="{% url 'product:home' %}">Cancelar</a>
                                <input class="btn btn-danger btn-sm" type="submit" value="Confirmar">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--//container-fluid-->
    </div><!--//app-content-->	    
</div><!--//app-wrapper--> 
{% endblock %}