management_sistem/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('usuarios/', include("user.urls")),
    path('ordens/', include("order.urls")),
    path('produtos/', include("product.urls")),
    path('', include("dashboard.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Sistema de Gestão'
admin.site.index_title= 'Administração'
admin.site.site_title = 'Seja bem vindo a gestão de produtos e serviços'

order/urls.py
from django.urls import path


from .views import (SaleListView, 
                    SaleDetailView, 
                    SaleCreateView,
                    SaleProductAdd,
                    SaleEditView,
                    SaleDeleteView,
                    ProductDeleteView,
                    EditProductView)

app_name= 'order'

urlpatterns = [
    path('', SaleListView.as_view(), name='list'),
    path('detalhe/<slug:slug>/', SaleDetailView.as_view(), name='detail'),
    path('criar/', SaleCreateView.as_view(), name='new'),
    path('add_product/<int:sale>/', SaleProductAdd.as_view(), name='add_product'),
    path('editar/<int:sale>/', SaleEditView.as_view(), name='edit'),
    path('excluir/<int:sale>/', SaleDeleteView.as_view(), name='delete'),
    path('excluir-produto/<int:item>/', ProductDeleteView.as_view(), name='delete_product'),
    path('editar-produto/<int:item>/', EditProductView.as_view(), name='edit_product'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user import views as user_views

app_name = 'user'

urlpatterns = [
    # Login
    path('login', auth_views.LoginView.as_view(
        template_name='user/login.html'), name='login'),
    # Logout
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'),
         name='logout'),
    # Cadastro
    path('registro/', user_views.register, name='register'),
    # Perfil
    path('perfil/', user_views.profile, name='profile'),
    
    path('perfil/update/', user_views.profile_update,
         name='update'),    
    ]

order/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Sum, F, FloatField
from django.db.models.signals import post_save
from django.dispatch import receiver
from autoslug import AutoSlugField

from .managers import SaleManager
from product.models import Product

STATUS = (
        ('Pago','Pago'),
        ('Pendente', 'Pendente'),
        ('Cancelado', 'Cancelado'),
    )   

class Sale(models.Model):     
    reference_code = models.IntegerField('Código de Referência')
    slug = AutoSlugField(unique=True, always_update=False, populate_from="reference_code", default=None)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    price= models.DecimalField('Preço', decimal_places=2, max_digits=10, default=0)
    discount = models.DecimalField('Desconto', decimal_places=2, max_digits=5, blank=True, default=0)
    nfe=models.BooleanField('Nota Fiscal Eletronica', default=False)
    status = models.CharField('Status',choices=STATUS,max_length=50, null=True, blank=True)
    date = models.DateField('Data',auto_now_add=True)
    
    objects= SaleManager()
    
    def __str__(self):
        return f'Venda - {self.id}'
    
    def get_absolute_url(self):
        return reverse("order:detail", kwargs={"slug": self.slug})
    
    def total_price(self): 
        total = self.saleitem_set.all().aggregate(
            total_sale=Sum((F('quantity')* F('product__price')) - F('discount'), output_field=FloatField())
        )['total_sale'] or 0
        total = total - float(self.discount) # TODO - self.imposto
        self.price = total
        Sale.objects.filter(id=self.id).update(price=total)        
    
    def products(self):
        products = self.saleitem_set.all()
        return products     
   
    class Meta :
        permissions = (
            ('nfe_change', 'Usuário pode alterar parâmetro NF-e'),
        )
        verbose_name = "Vendas"
        verbose_name_plural = "Vendas"
        
class SaleItem(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    discount = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    
    def __str__(self):
        return f'{self.product.name} - {self.sale.id}'
    
    class Meta :
        verbose_name = 'Item da Venda'
        verbose_name_plural = 'Itens da Venda'

class Order(models.Model): 
    sale = models.ForeignKey(Sale,on_delete=models.CASCADE, related_name="sale", blank=True, null=True,)   
    slug = AutoSlugField(unique=True, always_update=False, populate_from="customer", default=None)
    reference_code = models.IntegerField('Código de Referência')
    internal_code=models.IntegerField('Código Interno', blank=True, null=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    price = models.DecimalField('Preço',max_digits=10, decimal_places=2)
    description = models.TextField('Descição 1',max_length=500, blank=True)
    description_2 = models.TextField('Descição 2',max_length=500, blank=True)
    date = models.DateField('Data',auto_now_add=True)

    def __str__(self):
        return f'Ordem - {self.customer} - {self.id}'   
    
    class Meta :
        verbose_name = "Ordem"
        verbose_name_plural = "Ordens"
        
        
@receiver(post_save, sender=SaleItem)
def update_sale_price(sender, instance,**kwargs):
    instance.sale.total_price()
        
@receiver(post_save, sender=Sale)
def update_sale_price2(sender, instance,**kwargs):
    instance.total_price()

order/forms.py
from django import forms
from order.models import SaleItem

class SaleForm(forms.Form):
    reference_code = forms.IntegerField(label='Código de Referência')
    customer = forms.ChoiceField(label='Cliente')
    discount = forms.DecimalField(label='Desconto', decimal_places=2, max_digits=5, )

class ProductForm(forms.Form):
    product_id = forms.CharField(label='Produto')
    quantity = forms.IntegerField(label='Quantidade')
    discount = forms.DecimalField(label='Desconto', max_digits=5, decimal_places=2)

class SaleItemModelForm(forms.ModelForm):
    sale = forms.CharField(label='Venda')
    product = forms.CharField(label='Produto')
    quantity = forms.IntegerField(label='Quantidade')
    discount = forms.DecimalField(label='Desconto', max_digits=5, decimal_places=2)
    class Meta:
        model = SaleItem
        fields = '__all__'
        

order/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, View

from user.models import User
from .forms import SaleForm, ProductForm, SaleItemModelForm
from .models import Sale, SaleItem, Product

class SaleListView(ListView):
    
    model = Sale
    paginate_by = 15
    template_name= 'order/sale_list.html'    
    
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        return context

class SaleDetailView(DetailView):
    
    model = Sale
    template_name = 'order/sale_detail.html'

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        return context

class SaleCreateView(View):

    def get(self, request):
        return render(request, 'order/sale_form.html')

    def post(self,request):
        data = {}
        data['form_sale'] = SaleForm()
        data['reference_code'] = request.POST['reference_code']
        data['customer']= request.POST['customer']
        data['discount'] = float(request.POST['discount'])
        data['sale']=request.POST['sale_id']

        if data['sale']:
            sale = Sale.objects.get(id=data['sale'])
            sale.discount = data['discount']
            sale.reference_code = data['reference_code']
            sale.customer = User.objects.get(id=data['customer'])
            sale.save()
        else :
            sale = Sale.objects.create(
                reference_code=data['reference_code'],discount=data['discount'], customer= User.objects.get(id=data['customer'])
            )
            itens = sale.saleitem_set.all()
            data['sale_obj']=sale
            data['itens']=itens

        return render(request, 'order/sale_form.html', data)

class SaleProductAdd(View):

    def get(self, request):
        return render(request, 'order/sale_form.html')


    def post(self, request, sale):
        
        data={}
        
        item = SaleItem.objects.filter(
            product=Product.objects.get(id=request.POST['product_id']),
            sale=Sale.objects.get(id=sale))
                
        if item.exists() :
            data['message']='Item ja incluido no pedido, favor editar'
            item = item[0]
        else :                
            item = SaleItem.objects.create(
                product=Product.objects.get(id=request.POST['product_id']),quantity=request.POST['quantity'],
                discount=request.POST['discount'], sale=Sale.objects.get(id=sale)
            )
            
        data['item']=item
        data['form_item']=ProductForm()
        data['reference_code']=item.sale.reference_code
        data['discount']=item.sale.discount
        data['sale_id']=item.sale.id            
        data['sale_obj']=item.sale
        data['itens']=item.sale.saleitem_set.all()

        return render(request, 'order/sale_form.html', data)

class SaleEditView(View):
    
    def get(self, request, sale):
        data= {}
        sale= Sale.objects.get(id=sale)
        data['form_item']= ProductForm()        
        data['reference_code']=sale.reference_code
        data['discount']=sale.discount
        data['sale_id']=sale.id
        data['sale_obj']=sale
        data['itens']=sale.saleitem_set.all()
        
        return render(request, 'order/sale_edit.html', data)
    
class SaleDeleteView(View):
    
    def get (self, request,sale):
        sale = Sale.objects.get(id=sale)        
        return render(request, 'order/sale_delete.html', {'sale':sale})
        
    def post (self, request,sale):
        sale = Sale.objects.get(id=sale)
        sale.delete()
        return redirect('order:list')

class ProductDeleteView(View):
    
    def get (self, request,item):
        sale_item = SaleItem.objects.get(id=item)
        return render(request, 'order/delete-product.html', {'sale_item':sale_item})
    
    def post (self, request, item):
        sale_item = SaleItem.objects.get(id=item)
        sale_id = sale_item.sale.id
        sale_item.delete()
        request.method= 'GET'
        return redirect('order:edit', sale=sale_id)
    
class EditProductView(View):
    
    def get (self, request, item):
        sale_item = SaleItem.objects.get(id=item)
        form = SaleItemModelForm(instance=sale_item)
        
        return render(request, 'order/edit_product.html', {'sale_item':sale_item, 'form': form})
    
    def post (self, request, item):
        sale_item = SaleItem.objects.get(id=item)
        sale_item.quantity = request.POST['quantity']
        sale_item.discount = request.POST['discount']
        sale_item.sale = Sale.objects.get(id=request.POST['sale'])
        sale_item.product = Product.objects.get(id=request.POST['product'])       
        sale_item.save()
        sale_id= sale_item.sale.id
         
        return redirect('order:edit', sale=sale_id)

templates/order/delete-product.html
{% extends 'base.html' %}
{% block title %}Deletar Item{{ sale_item.product.name }}{% endblock %}

{% load crispy_forms_tags %}
{% block content %}


<div class="app-wrapper">	    
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
            <div class="row col-10">
                <div class="row my-4">
                    <div class="col-md-6 offset-md-3">
                        <div class="border p-3 bg-white">
                            <h3>Excluir Produto</h3>
                            <hr>
                            <form method="POST">
                                <div class="alert alert-danger">
                                    <h4>Tem certeza que deseja excluir o produto "{{ sale_item.product.name }}"  da lista ? </h4>
                                </div>
                                {% csrf_token %}
                                {{ form|crispy }}
                                <a class="btn btn-secondary btn-sm" href="{% url 'order:list' %}">Cancelar</a>
                                <input class="btn btn-danger btn-sm" type="submit" value="Confirmar">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--//container-fluid-->
    </div><!--//app-content-->	    
</div><!--//app-wrapper--> 
{% endblock %}

templates/order/edit_product.html
{% extends 'base.html'%}
{% block content %}

{% load crispy_forms_tags %}


<div class="app-wrapper">	    
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
            <div class="row col-10">
                <div class="row my-4">
                    <h1> Editando item {{ sale_item }}</h1>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Atualizar</button>
                    </form>
                 </div>
            </div>
        </div><!--//container-fluid-->
    </div><!--//app-content-->	    
</div><!--//app-wrapper--> 

{% endblock content%}

templates/order/sale_delete.html
{% extends 'base.html' %}
{% block title %}Deletar Venda{% endblock %}

{% load crispy_forms_tags %}
{% block content %}


<div class="app-wrapper">	    
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
            <div class="row col-10">
                <div class="row my-4">
                    <div class="col-md-6 offset-md-3">
                        <div class="border p-3 bg-white">
                            <h3>Excluir Produto</h3>
                            <hr>
                            <form method="POST">
                                <div class="alert alert-danger">
                                    <h4>Tem certeza que deseja excluir a venda "{{ sale.reference_code }}" ? <br>Lembre-se que essa ação é irreversível</h4>
                                </div>
                                {% csrf_token %}
                                {{ form|crispy }}
                                <a class="btn btn-secondary btn-sm" href="{% url 'order:list' %}">Cancelar</a>
                                <input class="btn btn-danger btn-sm" type="submit" value="Confirmar">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--//container-fluid-->
    </div><!--//app-content-->	    
</div><!--//app-wrapper--> 
{% endblock %}

templates/order/sale_detail.html
{%extends 'base.html'%}
{% block title %}Venda {{sale.reference_code }}{%endblock title %}
{% block content %}


<div class="app-wrapper">
	    
	    <div class="app-content pt-3 p-md-3 p-lg-4">
		    <div class="container-xl">

                <div class="row g-3 mb-4 align-items-center justify-content-between">                                     
                    <div class="app-page-title mb-0">Venda - {{sale.reference_code}} Resumo :</div>
					<div class='row col-2'>
						<a  class='btn btn-primary 'href='{% url 'order:edit' sale.id%}'>Editar</a>
						<a class='btn btn-danger' href='{% url 'order:delete' sale.id%}'>Excluir</a>
					</div>
                <div class="row g-4 mb-4">
                    <div class="col-6 col-lg-3">
					    <div class="app-card app-card-stat shadow-sm h-100">
						    <div class="app-card-body p-3 p-lg-4">
							    <h4 class="stats-type mb-1">Cliente</h4>
							    <div class="stats-figure">{{ sale.customer}}</div>							    
						    </div><!--//app-card-body-->
					    </div><!--//app-card-->
				    </div><!--//col-->  
                    <div class="col-6 col-lg-3">
					    <div class="app-card app-card-stat shadow-sm h-100">
						    <div class="app-card-body p-3 p-lg-4">
							    <h4 class="stats-type mb-1">Preço Final</h4>
							    <div class="stats-figure">{{ sale.price}}</div>							    
						    </div><!--//app-card-body-->
					    </div><!--//app-card-->
				    </div><!--//col-->  
                    <div class="col-6 col-lg-3">
					    <div class="app-card app-card-stat shadow-sm h-100">
						    <div class="app-card-body p-3 p-lg-4">
							    <h4 class="stats-type mb-1">Desconto</h4>
							    <div class="stats-figure">{{ sale.discount}}</div>							    
						    </div><!--//app-card-body-->
					    </div><!--//app-card-->
				    </div><!--//col-->  
                    <div class="col-6 col-lg-3">
					    <div class="app-card app-card-stat shadow-sm h-100">
						    <div class="app-card-body p-3 p-lg-4">
							    <h4 class="stats-type mb-1">Data da compra</h4>
							    <div class="stats-figure">{{ sale.date|date:"j D b"}}</div>							    
						    </div><!--//app-card-body-->
					    </div><!--//app-card-->
				    </div><!--//col-->                                        
                </div><!-- Row --> 
                <div class="app-page-title mb-0">Produtos da venda : </div>  
                <div class="row g-4 mb-4">
                {% for product in sale.products %}
                    <div class="col-6 col-lg-3">
					    <div class="app-card app-card-stat shadow-sm h-100">
						    <div class="app-card-body p-3 p-lg-4">
							    <h4 class="stats-type mb-1">{{product.product.name}}</h4>
							    <div class="stats-figure">{{ product.quantity }}</div>							    
						    </div><!--//app-card-body-->
					    </div><!--//app-card-->
                    </div> 
                {% endfor %} 
                </div>  
                
                </div>  
		    </div><!--//container-fluid-->
	    </div><!--//app-content-->    
	    
    </div><!--//app-wrapper-->    
{% endblock content %} 

templates/order/sale_edit.html
{% extends "base.html"%}
{% block title %}Nova Ordem de Venda {% endblock title%}

{% block content %}

{% load crispy_forms_tags %}

<div class="app-wrapper">	    
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
            <h1 class="app-page-title">Cabeçalho Venda {{ sale_obj.reference_code }} </h1>
            <h5> Preço {{ sale_obj.price }}</h5>
            <form method="POST" action='{% url 'order:new' %}'>
            {% csrf_token %}
                <label for='reference_code'>Código de Referência</label><br>
                <input type='text' class='form-control'name='reference_code' value="{{reference_code}}" placeholder='9999'>
                <label for='customer'>Cliente</label><br>
                <input type='text' class='form-control'name='customer' value='{{customer}}' placeholder='Só números'>
                <label for='discount'>Desconto</label><br>
                <input type='number' class='form-control'name='discount' value='{{discount}}' placeholder='0,00'>
                <input type="hidden" name="sale_id" value='{{sale_obj.id}}'>
                <input class="btn btn-primary"type="submit" value="Criar">
            </form>
            {% if sale_obj %}
                <h4>Adicionar Produtos </h4>
                <form action='{% url 'order:add_product' sale_obj.id %}' method='POST'>
                    {% csrf_token %}
                    <label for='product_id'>Id do Produto</label><br>
                    <input type='text' class='form-control'name='product_id' value="{{product_id}}" placeholder='9999'>
                    <label for='quantity'>Quantidade</label><br>
                    <input type='number' class='form-control'name='quantity' value="{{quantity}}" placeholder='1~99'>
                    <label for='discount'>Desconto</label><br>
                    <input type='number' class='form-control'name='discount' value="{{discount}}" placeholder='0'> 
                    <button class="btn btn-primary" type="submit">Incluir</button>
                </form>
                <h2>Listagem de Itens :</h2>
                <table class="table">
                    <thread>
                        <tr>
                            <th scope="col">Id</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Quantidade</th>
                            <th scope="col">Desconto</th>
                            <th scope="col">Editar</th>
                            <th scope="col">Excluir</th>
                        </tr>
                    </thread>
                    <tbody>
                    {% for item in itens %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.product.name }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.discount }}</td>
                            <td><a class='btn btn-secondary ' href='{% url 'order:edit_product' item.id %}'>Editar</a></td>
                            <td><a class='btn btn-danger ' href='{% url 'order:delete_product' item.id %}'>Excluir</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div><!--//container-fluid-->
    </div><!--//app-content-->	    
</div><!--//app-wrapper-->  

{% endblock content%}

templates/order/sale_form.html
{% extends "base.html"%}
{% block title %}Nova Ordem de Venda {% endblock title%}

{% block content %}

{% load crispy_forms_tags %}

<div class="app-wrapper">	    
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
        {% if message %}
            {% include 'messages/order_message.html' %}
        {% endif %}

            <h1 class="app-page-title">Cabeçalho Venda {{ sale_obj.reference_code }} </h1>
            <h5> Preço {{ sale_obj.price }}</h5>
            <h5> Desconto {{ sale_obj.discount }}</h5>

            <form method="POST" action='{% url 'order:new' %}'>
            {% csrf_token %}
                <label for='reference_code'>Código de Referência</label><br>
                <input type='text' class='form-control'name='reference_code' value="{{reference_code}}" placeholder='9999'>
                <label for='customer'>Cliente</label><br>
                <input type='text' class='form-control'name='customer' value='{{customer}}' placeholder='Só números'>
                <label for='discount'>Desconto</label><br>
                <input type='number' class='form-control'name='discount' value='{{discount}}' placeholder='0,00'>
                <input type="hidden" name="sale_id" value='{{sale_obj.id}}'>
                <input class="btn btn-primary"type="submit" value="Criar">
            </form>

            {% if sale_obj %}
                <h4>Adicionar Produtos </h4>
                <form action='{% url 'order:add_product' sale_obj.id %}' method='POST'>
                    {% csrf_token %}
                    <label for='product_id'>Id do Produto</label><br>
                    <input type='text' class='form-control'name='product_id' value="{{product_id}}" placeholder='9999'>
                    <label for='quantity'>Quantidade</label><br>
                    <input type='number' class='form-control'name='quantity' value="{{quantity}}" placeholder='1~99'>
                    <label for='discount'>Desconto</label><br>
                    <input type='number' class='form-control'name='discount' value="{{discount}}" placeholder='0'> 
                    <button class="btn btn-primary" type="submit">Incluir</button>
                </form>
                <h2>Listagem de Itens :</h2>
                <table class="table">
                    <thread>
                        <tr>
                            <th scope="col">Id</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Quantidade</th>
                            <th scope="col">Desconto</th>
                            <th scope="col">Editar</th>
                            <th scope="col">Excluir</th>
                        </tr>
                    </thread>
                    <tbody>
                    {% for item in itens %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.product.name }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.discount }}</td>
                            <td><a class='btn btn-secondary ' href='{% url 'order:edit_product' item.id %}'>Editar</a></td>
                            <td><a class='btn btn-danger ' href='{% url 'order:delete_product' item.id %}'>Excluir</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div><!--//container-fluid-->
    </div><!--//app-content-->	    
</div><!--//app-wrapper-->  

{% endblock content%}

templates/order/sale_list.html
{%extends 'base.html'%}
{% load static %}
{% block title %}Ordens{% endblock %}

{% block content %}
<div class="app-wrapper">
	    
	    <div class="app-content pt-3 p-md-3 p-lg-4">
		    <div class="container-xl">
			    
			    <div class="row g-3 mb-4 align-items-center justify-content-between">
				    <div class="col-auto">
			            <h1 class="app-page-title mb-0">Ordens de Venda<a class='btn btn-primary' href='{% url 'order:new'%}'>Nova Venda</a> </h1>
				    </div>
				    <div class="col-auto">
					     <div class="page-utilities">
						    <div class="row g-2 justify-content-start justify-content-md-end align-items-center">
							    <div class="col-auto">						    
								    <a class="btn app-btn-secondary" href="#">
									    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-download me-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                                            <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                                        </svg>
									    Baixar CSV									</a>
							    </div>
						    </div><!--//row-->
					    </div><!--//table-utilities-->
				    </div><!--//col-auto-->
			    </div><!--//row-->  

				<div class="tab-content" id="orders-table-tab-content">
			        <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
					    <div class="app-card app-card-orders-table shadow-sm mb-5">
						    <div class="app-card-body">
							    <div class="table-responsive">
							        <table class="table app-table-hover mb-0 text-left">
										<thead>
											<tr>
												<th class="cell">Venda</th>
												<th class="cell">Produto</th>
												<th class="cell">Cliente</th>
												<th class="cell">Data</th>
												<th class="cell">Status</th>
												<th class="cell">Total</th>
												<th class="cell"></th>
											</tr>
										</thead>
										<tbody>
                                            {% for sale in object_list %}
                                            <tr>
												<td class="cell">#{{sale.reference_code}}</td>
												<td class="cell"><span class="truncate">Lorem ipsum</span></td>
												<td class="cell">{{sale.customer}}</td>
												<td class="cell"><span>{{sale.date|date:"d D M"}}</span></td>
												<td class="cell"><span class="badge bg-success">Pago</span></td>
												<td class="cell">${{sale.price}}</td>
												<td class="cell"><a class="btn-sm app-btn-secondary" href="{{sale.get_absolute_url}}">Detalhes</a></td>												
											</tr>
                                            	{% empty %}
                                            <h1> Não existem ordens de venda ainda </h1>
                                            {% endfor %}		
										</tbody>
									</table>
						        </div><!--//table-responsive-->
						       
						    </div><!--//app-card-body-->		
						</div><!--//app-card-->
						{% include 'pagination.html'%}
			        </div><!--//tab-pane-->			    
		    </div><!--//container-fluid-->
	    </div><!--//app-content-->
	    
	    
    </div><!--//app-wrapper-->    	

{% endblock content %}